// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9b4EXEcRcH_38gPMenW2sr1jus2qj_dE',
    appId: '1:871883896435:web:c19c376d5120e23524dc06',
    messagingSenderId: '871883896435',
    projectId: 'auth-production-71a58',
    authDomain: 'auth-production-71a58.firebaseapp.com',
    storageBucket: 'auth-production-71a58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6RKKcG8Cu9diKkCD-Ug1yK7-4QKhi_F8',
    appId: '1:871883896435:android:6c7a7a87488234cf24dc06',
    messagingSenderId: '871883896435',
    projectId: 'auth-production-71a58',
    storageBucket: 'auth-production-71a58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8HdDKxltpfoaDj2jjZTS62TvXGKZEabA',
    appId: '1:871883896435:ios:6c19633fbab2213324dc06',
    messagingSenderId: '871883896435',
    projectId: 'auth-production-71a58',
    storageBucket: 'auth-production-71a58.appspot.com',
    iosClientId: '871883896435-tusbqj5foduom8a1a0khj4tqm00oa0fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8HdDKxltpfoaDj2jjZTS62TvXGKZEabA',
    appId: '1:871883896435:ios:6c19633fbab2213324dc06',
    messagingSenderId: '871883896435',
    projectId: 'auth-production-71a58',
    storageBucket: 'auth-production-71a58.appspot.com',
    iosClientId: '871883896435-tusbqj5foduom8a1a0khj4tqm00oa0fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9b4EXEcRcH_38gPMenW2sr1jus2qj_dE',
    appId: '1:871883896435:web:f6fb8fbd33d0a95e24dc06',
    messagingSenderId: '871883896435',
    projectId: 'auth-production-71a58',
    authDomain: 'auth-production-71a58.firebaseapp.com',
    storageBucket: 'auth-production-71a58.appspot.com',
  );

}